airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls", namespace='flights')),
    path("users/", include("users.urls", namespace='users')),
]

airline/flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path('', views.index, name='index'),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int>:flight_id/book", views.book, name="book")
]

airline/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

airline/flights/models.py
from django.db import models


# defining a airport
class Airport(models.Model):
    code = models.CharField( max_length=4)
    city = models.CharField(max_length=64)

    def __str__(self) -> str:
        # return super().__str__()
        return f"{self.city} ({self.code})"

# defining a flight (which has 2 airports)
class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='departures')
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='arrivals')
    duration = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.id} : {self.origin} to {self.destination} of {self.duration} hours"

# defining a paasenger model
class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name='passengers')

    def __str__(self) -> str:
        return f"{self.first} {self.last}"

airline/users/models.py
from django.db import models

# Create your models here.

airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Flight, Airport, Passenger

# index view
def index(request):
    return render(request, 'flights/index.html', {
        "flights": Flight.objects.all()
    })


# gives information about a flight and list of passengers
def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    passengers= flight.passengers.all()
    non_passengers = Passenger.objects.exclude(flights=flight).all()
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers":passengers,
        "non_passengers": non_passengers,
    })

# booking a flight
def book(request, flight_id):
    
    # for a POST r request, add a new flight
    if request.method == "POST":

        # accessing the flight
        flight = Flight.objects.get(pk=flight_id)

        # finding the passenger id if from the submitted form data
        passenger_id = int(request.POST["passenger"])

        # finding the passenger based on id
        passenger = Passenger.objects.get(pk=passenger_id)

        # adding the passenger to the flight
        passenger.flights.add(flight)

        # redirect user to flight page
        return HttpResponseRedirect(reverse("flights:flight", args=(flight_id,)))

airline/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# main login page

def index(request):
    # if no user is signed in, return to the login page
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # check if username and password are correct, reutrning User Object
        user = authenticate(request, username=username, password=password)

        # if user object is returned, log in and route to index page
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        # otherwise login pgae iwht new context
        else:
            return render(request, "users/login.html", {
                "message " : "Invalid Credentials"
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
                "message": "Logged Out"
            })

airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{flight.id}}</h1>
    <ul>
        <li>Origin: {{flight.origin}}</li>
        <li>Destination: {{flight.destination}}</li>
        <li>Duration: {{flight.duration}}</li>
    </ul>
    
    <h2>Passengers:</h2>
    <ul>
        {% for passenger in passengers %}
        <li>{{ passenger.name }}</li>
        {% empty %}
        <li>No passengers.</li>
        {% endfor %}
    </ul>
    
    <form action="{% url 'flights:book' flight.id %}" method="post">
        <h3>Add Passenger</h3>
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
            <option value="{{passenger.id}}"> {{passenger}}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
    
    <a href="{% url 'flights:index' %}">All Flights</a>
    {% endblock body %}
    

airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights</h1>
    <ul>
        {% for flight in flights %}
            <li><a href="{% url 'flights:flight' flight.id %}">Flight {{flight.id}}</a> : {{ flight.origin }} to {{ flight.destination }}</li>
        {% endfor %}
    </ul>
{% endblock%}

airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Flights</title>
</head>

<body>
    {% block  body %}
    {% endblock body%}
</body>
</html>

airline/users/templates/users/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>

<body>
    {% block  body %}
    {% endblock body%}
</body>
</html>

airline/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    {% if message %}
        <div>{{message}}</div>
    {% endif %}

    <form action="{% url 'users:login' %}" method='post'>
        {% csrf_token %}
        <input type="text", name='username', placeholder='Username'>
        <input type="password" name="password" placeholder="Password">
        <input type="submit", value="Login">
    </form>
{% endblock body %}

airline/users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:logout' %}">Log Out</a>
{% endblock %}